# Generated by Django 2.1.7 on 2019-03-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=18)),
                ('realname', models.CharField(max_length=18)),
                ('password', models.CharField(max_length=18)),
                ('age', models.IntegerField(max_length=8)),
                ('sex', models.CharField(max_length=3)),
                ('telephone', models.IntegerField(max_length=12)),
                ('require', models.CharField(max_length=500)),
                ('img', models.ImageField(null=True, upload_to='static/img/img')),
                ('name', models.CharField(max_length=100, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
